### ISSUE TITLE
Problem To login...

### ISSUE THREAD

**Issue by alesoft73** [FuzzyMistborn/python-eufy-security#13]
HI !
Many thanks for this component.
I have install the custom componet , configure the configuration.yaml username and password (second account)

But i receive an error, can’t configure…

(MainThread) [homeassistant.setup] Setup failed for eufy_security: No setup function defined.

**Comment by bachya** [comment]
Please take a look at [these installation instructions](https://github.com/nonsleepr/ha-eufy-security) and post back here if you have issues.

**Comment by bachya** [comment]
Please take a look at [these installation instructions](https://github.com/nonsleepr/ha-eufy-security) and post back here if you have issues.

**Comment by alesoft73** [comment]
Many thanks, you have update the component.
I see a new "Eufy Security" integration in Home Assistant's "Configuration -> Integrations" tab, but when press configure don't open anything.
I have 0.102.2 version.
Thanks

**Comment by bachya** [comment]
What do the logs say?

>Is possible to configure the Cam directly into the configuration.yaml?

Yep!

**Comment by alesoft73** [comment]
In the log i have this error:

019-12-10 17:37:43 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 40, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 136, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 122, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 163, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 48, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 90, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 89, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 132, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/eufy_security/config_flow.py", line 56, in async_step_user
    user_input[CONF_USERNAME], user_input[CONF_PASSWORD], session
  File "/usr/local/lib/python3.7/site-packages/eufy_security/api.py", line 122, in async_login
    await api.async_update_device_info()
  File "/usr/local/lib/python3.7/site-packages/eufy_security/api.py", line 54, in async_update_device_info
    for device_info in devices_resp["data"]:

**Comment by bachya** [comment]
That looks cut-off – what's the end of the call stack?

**Comment by alesoft73** [comment]
Noy i receive this error :
2019-12-10 20:15:41 ERROR (MainThread) [homeassistant.setup] Setup failed for eufy_security: No setup function defined.
