### ISSUE TITLE
Forbidden when accessing get_devs_list

### ISSUE THREAD

**Issue by jrlambs** [FuzzyMistborn/python-eufy-security#72]
**Describe the bug**

**To Reproduce**
1. Install with pip3, 'pip3 install python-eufy-security'
2. Create program exactly like the demo application that starts rtsp stream
3. update credentials to my own
4. run the program python3 program.py

**Expected behavior**
program connects successfully and lists device details

**Additional context**
In reality I get an error. 

`python3 blah.py
Traceback (most recent call last):
  File "/Users/jrlambs/projects/python/eufy/blah.py", line 30, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/jrlambs/projects/python/eufy/blah.py", line 12, in main
    api = await async_lo websession)
  File "/Users/jrlambs/Library/Python/3.9/lib/python/site-packages/eufy_security/api.py", line 130, in async_login
    await api.async_update_device_info()
  File "/Users/jrlambs/Library/Python/3.9/lib/python/site-packages/eufy_security/api.py", line 57, in async_update_device_info
    devices_resp = await self.request("post", "app/get_devs_list")
  File "/Users/jrlambs/Library/Python/3.9/lib/python/site-packages/eufy_security/api.py", line 114, in request
    raise RequestError(
eufy_security.errors.RequestError: There was an unknown error while requesting app/get_devs_list: 403, message='Forbidden', url='https://security-app.eufylife.com/v1/app/get_devs_list`

**Comment by FuzzyMistborn** [comment]
Please see the notice in the Readme.  This project is unmaintained.
